### ISSUE TITLE
Does not work with recursive types

### ISSUE THREAD

**Issue by pathikrit** [kifi/json-annotation#2]
``` scala
import com.kifi.macros.json

@json case class Person(name: String, children: Option[Set[Person]])
```

I wish the library detects recursive types and uses Play's `lazyFormat` macro...

**Comment by martinraison** [comment]
This is a limitation of the underlying `Json.format[T]` macro provided by Play. Some recursive types are already supported though, for example `case class Person(name: String, children: Set[Person])`. If Play's macro gets updated in the future, this problem will be automatically solved.
