### ISSUE TITLE
The single-field class formatter should support standard Play format

### ISSUE THREAD

**Issue by evictor** [kifi/json-annotation#4]
We would love to use your plugin at Gravity, but unfortunately it would require a difficult migration for certain single-value case classes that use the standard Play format (e.g. `{"name":"Bob"}` for `case class Person(name: String)`). The problem is that we have many such classes and serializations being stored and transmitted among many apps; to use your plugin as-is we would have to perform a difficult migration involving hundreds of servers.

Would it be possible for you to release a patch to support "backwards compatibility" with the default Play format for single-value case classes? If not, I suppose I could do my best to submit a PR with one, but chances are you'll be able to whip that out much more quickly as I have no macro experience...

**Comment by erraggy** [comment]
+1

**Comment by hindog** [comment]
+1

**Comment by adriangrealish** [comment]
+1

**Comment by TreyThree** [comment]
+1

**Comment by stkem** [comment]
https://github.com/kifi/json-annotation/pull/5

**Comment by evictor** [comment]
:+1: :)
