### ISSUE TITLE
There is no version 0.2 for 2.10.x

### ISSUE THREAD

**Issue by pathikrit** [kifi/json-annotation#7]
I checked here: https://oss.sonatype.org/content/repositories/releases/com/kifi/
See: https://travis-ci.org/pathikrit/metarest/builds/50177041

Can you deploy? I am writing a library that depends on your library and needs it to work across 2.10.x and 2.11.x
https://github.com/pathikrit/metarest

**Comment by andrewconner** [comment]
Should be fixed! Thanks @martinraison! https://oss.sonatype.org/content/repositories/releases/com/kifi/
